require "roman"

describe("Roman Numeral encoder/decoder.", function()
  describe("Test decoding (Roman -> Arabic) functionality.", function()
    it("converts the year 1990", function()
      assert.are.same( ToNumeral( "MCMXC"), 1990 )
    end)
    it("converts the year 2008, with many zeroes", function()
      assert.are.same( ToNumeral( "MMVIII"), 2008 )
    end)
    it("converts the year 1666, long-ago", function()
      assert.are.same( ToNumeral( "MDCLXVI"), 1666 )
    end)
  end)
  describe("Test encoding (Arabic -> Roman) functionality.", function()
    it("converts the year 2017", function()
      assert.are.same( FromNumeral ( 2017), "MMXVII" )
    end)
    it("converts the year 1099", function()
      assert.are.same( FromNumeral ( 1099), "MXCIX" )
    end)
    it("converts the year 527", function()
      assert.are.same( FromNumeral ( 527), "DXXVII" )
    end)
  end)
  describe("Property-based testing encoding -> decoding -> encoding.", function()
    it("tries all the things.", function()
      for i = 500, 1500, 1 do
        assert.are.same( ToNumeral(FromNumeral(i)), i )
      end
    end)
  end)
end)
